name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: # Node.js version https://github.com/nodejs/release#release-schedule
          - 20 # Maintenance LTS
          - 22 # Active LTS
          - 24 # Current
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: 💚 Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: 🚧 Install Dependencies
        run: npm ci
      - name: 📦 Build
        run: npm run build
      - name: 🧪 Run Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
